theme: minima
title: All about me
author: Omer
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
 I love playing sports (especially soccer) and I love playing video games, I also like reading exciting novels that have adventures

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
